List dummyData = [
  {
    "breeds": [
      {
        "weight": {"imperial": "6 - 11", "metric": "3 - 5"},
        "id": "bomb",
        "name": "Bombay",
        "cfa_url": "http://cfa.org/Breeds/BreedsAB/Bombay.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/bombay",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/bombay",
        "temperament": "Affectionate, Dependent, Gentle, Intelligent, Playful",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description":
            "The the golden eyes and the shiny black coa of the Bopmbay is absolutely striking. Likely to bond most with one family member, the Bombay will follow you from room to room and will almost always have something to say about what you are doing, loving attention and to be carried around, often on his caregiver's shoulder.",
        "life_span": "12 - 16",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Small black Panther",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 3,
        "grooming": 1,
        "health_issues": 3,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 4,
        "stranger_friendly": 4,
        "vocalisation": 5,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Bombay_(cat)",
        "hypoallergenic": 0,
        "reference_image_id": "5iYq9NmT1"
      }
    ],
    "id": "5iYq9NmT1",
    "url": "https://cdn2.thecatapi.com/images/5iYq9NmT1.jpg",
    "width": 1250,
    "height": 650
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "5 - 10", "metric": "2 - 5"},
        "id": "drex",
        "name": "Devon Rex",
        "cfa_url": "http://cfa.org/Breeds/BreedsCJ/DevonRex.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/devon-rex",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/devon-rex",
        "temperament":
            "Highly interactive, Mischievous, Loyal, Social, Playful",
        "origin": "United Kingdom",
        "country_codes": "GB",
        "country_code": "GB",
        "description":
            "The favourite perch of the Devon Rex is right at head level, on the shoulder of her favorite person. She takes a lively interest in everything that is going on and refuses to be left out of any activity. Count on her to stay as close to you as possible, occasionally communicating his opinions in a quiet voice. She loves people and welcomes the attentions of friends and family alike.",
        "life_span": "10 - 15",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Pixie cat, Alien cat, Poodle cat",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 5,
        "grooming": 1,
        "health_issues": 3,
        "intelligence": 5,
        "shedding_level": 1,
        "social_needs": 5,
        "stranger_friendly": 5,
        "vocalisation": 1,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 1,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Devon_Rex",
        "hypoallergenic": 1,
        "reference_image_id": "4RzEwvyzz"
      }
    ],
    "id": "uUGt0UBzF",
    "url": "https://cdn2.thecatapi.com/images/uUGt0UBzF.jpg",
    "width": 1800,
    "height": 1800
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "7 - 14", "metric": "3 - 6"},
        "id": "esho",
        "name": "Exotic Shorthair",
        "cfa_url": "http://cfa.org/Breeds/BreedsCJ/Exotic.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/exotic-shorthair",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/exotic-shorthair",
        "temperament": "Affectionate, Sweet, Loyal, Quiet, Peaceful",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description":
            "The Exotic Shorthair is a gentle friendly cat that has the same personality as the Persian. They love having fun, don’t mind the company of other cats and dogs, also love to curl up for a sleep in a safe place. Exotics love their own people, but around strangers they are cautious at first. Given time, they usually warm up to visitors.",
        "life_span": "12 - 15",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Exotic",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 3,
        "dog_friendly": 3,
        "energy_level": 3,
        "grooming": 2,
        "health_issues": 3,
        "intelligence": 3,
        "shedding_level": 2,
        "social_needs": 4,
        "stranger_friendly": 2,
        "vocalisation": 1,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Exotic_Shorthair",
        "hypoallergenic": 0,
        "reference_image_id": "YnPrYEmfe"
      }
    ],
    "id": "32u84LkNG",
    "url": "https://cdn2.thecatapi.com/images/32u84LkNG.jpg",
    "width": 1280,
    "height": 848
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "4 - 10", "metric": "2 - 5"},
        "id": "csho",
        "name": "Colorpoint Shorthair",
        "cfa_url": "http://cfa.org/Breeds/BreedsCJ/ColorpointShorthair.aspx",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/colorpoint-shorthair",
        "temperament": "Affectionate, Intelligent, Playful, Social",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description":
            "Colorpoint Shorthairs are an affectionate breed, devoted and loyal to their people. Sensitive to their owner’s moods, Colorpoints are more than happy to sit at your side or on your lap and purr words of encouragement on a bad day. They will constantly seek out your lap whenever it is open and in the moments when your lap is preoccupied they will stretch out in sunny spots on the ground.",
        "life_span": "12 - 16",
        "indoor": 0,
        "lap": 1,
        "alt_names": "",
        "adaptability": 3,
        "affection_level": 4,
        "child_friendly": 4,
        "cat_friendly": 3,
        "dog_friendly": 4,
        "energy_level": 4,
        "grooming": 2,
        "health_issues": 2,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 4,
        "stranger_friendly": 2,
        "vocalisation": 5,
        "bidability": 4,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Colorpoint_Shorthair",
        "hypoallergenic": 0,
        "reference_image_id": "oSpqGyUDS"
      }
    ],
    "id": "Il3qBc63U",
    "url": "https://cdn2.thecatapi.com/images/Il3qBc63U.jpg",
    "width": 1000,
    "height": 1000
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "5 - 10", "metric": "2 - 5"},
        "id": "jbob",
        "name": "Japanese Bobtail",
        "cfa_url": "http://cfa.org/Breeds/BreedsCJ/JapaneseBobtail.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/japanese-bobtail",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/japanese-bobtail",
        "temperament":
            "Active, Agile, Clever, Easy Going, Intelligent, Lively, Loyal, Playful, Social",
        "origin": "Japan",
        "country_codes": "JP",
        "country_code": "JP",
        "description":
            "The Japanese Bobtail is an active, sweet, loving and highly intelligent breed. They love to be with people and play seemingly endlessly. They learn their name and respond to it. They bring toys to people and play fetch with a favorite toy for hours. Bobtails are social and are at their best when in the company of people. They take over the house and are not intimidated. If a dog is in the house, Bobtails assume Bobtails are in charge.",
        "life_span": "14 - 16",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Japanese Truncated Cat",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 5,
        "grooming": 1,
        "health_issues": 1,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 5,
        "stranger_friendly": 5,
        "vocalisation": 5,
        "experimental": 0,
        "hairless": 0,
        "natural": 1,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 1,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Japanese_Bobtail",
        "hypoallergenic": 0,
        "reference_image_id": "-tm9-znzl"
      }
    ],
    "id": "d8AjzQxLp",
    "url": "https://cdn2.thecatapi.com/images/d8AjzQxLp.jpg",
    "width": 1600,
    "height": 1041
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "7 - 15", "metric": "3 - 7"},
        "id": "ocic",
        "name": "Ocicat",
        "cfa_url": "http://cfa.org/Breeds/BreedsKthruR/Ocicat.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/ocicat",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/ocicat",
        "temperament":
            "Active, Agile, Curious, Demanding, Friendly, Gentle, Lively, Playful, Social",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description":
            "Loyal and devoted to their owners, the Ocicat is intelligent, confident, outgoing, and seems to have many dog traits. They can be trained to fetch toys, walk on a lead, taught to 'speak', come when called, and follow other commands. ",
        "life_span": "12 - 14",
        "indoor": 0,
        "alt_names": "",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 5,
        "grooming": 1,
        "health_issues": 3,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 5,
        "stranger_friendly": 5,
        "vocalisation": 3,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Ocicat",
        "hypoallergenic": 1,
        "reference_image_id": "JAx-08Y0n"
      }
    ],
    "id": "aJAsEA8uU",
    "url": "https://cdn2.thecatapi.com/images/aJAsEA8uU.jpg",
    "width": 1280,
    "height": 853
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "7 - 15", "metric": "3 - 7"},
        "id": "ocic",
        "name": "Ocicat",
        "cfa_url": "http://cfa.org/Breeds/BreedsKthruR/Ocicat.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/ocicat",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/ocicat",
        "temperament":
            "Active, Agile, Curious, Demanding, Friendly, Gentle, Lively, Playful, Social",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description":
            "Loyal and devoted to their owners, the Ocicat is intelligent, confident, outgoing, and seems to have many dog traits. They can be trained to fetch toys, walk on a lead, taught to 'speak', come when called, and follow other commands. ",
        "life_span": "12 - 14",
        "indoor": 0,
        "alt_names": "",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 5,
        "grooming": 1,
        "health_issues": 3,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 5,
        "stranger_friendly": 5,
        "vocalisation": 3,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Ocicat",
        "hypoallergenic": 1,
        "reference_image_id": "JAx-08Y0n"
      }
    ],
    "id": "fLJYKez7P",
    "url": "https://cdn2.thecatapi.com/images/fLJYKez7P.jpg",
    "width": 841,
    "height": 1024
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "5 - 10", "metric": "2 - 5"},
        "id": "orie",
        "name": "Oriental",
        "cfa_url": "http://cfa.org/Breeds/BreedsKthruR/Oriental.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/oriental",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/oriental",
        "temperament":
            "Energetic, Affectionate, Intelligent, Social, Playful, Curious",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description":
            "Orientals are passionate about the people in their lives. They become extremely attached to their humans, so be prepared for a lifetime commitment. When you are not available to entertain her, an Oriental will divert herself by jumping on top of the refrigerator, opening drawers, seeking out new hideaways.",
        "life_span": "12 - 14",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Foreign Type",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 5,
        "grooming": 1,
        "health_issues": 3,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 5,
        "stranger_friendly": 3,
        "vocalisation": 5,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Oriental_Shorthair",
        "hypoallergenic": 1,
        "reference_image_id": "LutjkZJpH"
      }
    ],
    "id": "UYp1-LQxI",
    "url": "https://cdn2.thecatapi.com/images/UYp1-LQxI.jpg",
    "width": 768,
    "height": 1024
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "5 - 11", "metric": "2 - 5"},
        "id": "sfol",
        "name": "Scottish Fold",
        "cfa_url": "http://cfa.org/Breeds/BreedsSthruT/ScottishFold.aspx",
        "vetstreet_url":
            "http://www.vetstreet.com/cats/scottish-fold-highland-fold",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/scottish-fold",
        "temperament":
            "Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving",
        "origin": "United Kingdom",
        "country_codes": "GB",
        "country_code": "GB",
        "description":
            "The Scottish Fold is a sweet, charming breed. She is an easy cat to live with and to care for. She is affectionate and is comfortable with all members of her family. Her tail should be handled gently. Folds are known for sleeping on their backs, and for sitting with their legs stretched out and their paws on their belly. This is called the \"Buddha Position\".",
        "life_span": "11 - 14",
        "indoor": 0,
        "alt_names": "Scot Fold",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 3,
        "grooming": 1,
        "health_issues": 4,
        "intelligence": 3,
        "shedding_level": 3,
        "social_needs": 3,
        "stranger_friendly": 3,
        "vocalisation": 1,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Scottish_Fold",
        "hypoallergenic": 0,
        "reference_image_id": "o9t0LDcsa"
      }
    ],
    "id": "K5Y06caiW",
    "url": "https://cdn2.thecatapi.com/images/K5Y06caiW.jpg",
    "width": 2816,
    "height": 2112
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "6 - 12", "metric": "3 - 5"},
        "id": "tonk",
        "name": "Tonkinese",
        "cfa_url": "http://cfa.org/Breeds/BreedsSthruT/Tonkinese.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/tonkinese",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/tonkinese",
        "temperament":
            "Curious, Intelligent, Social, Lively, Outgoing, Playful, Affectionate",
        "origin": "Canada",
        "country_codes": "CA",
        "country_code": "CA",
        "description":
            "Intelligent and generous with their affection, a Tonkinese will supervise all activities with curiosity. Loving, social, active, playful, yet content to be a lap cat",
        "life_span": "14 - 16",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Tonk",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 5,
        "grooming": 1,
        "health_issues": 1,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 5,
        "stranger_friendly": 5,
        "vocalisation": 5,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Tonkinese_(cat)",
        "hypoallergenic": 0,
        "reference_image_id": "KBroiVNCM"
      }
    ],
    "id": "t8oArUO-L",
    "url": "https://cdn2.thecatapi.com/images/t8oArUO-L.jpg",
    "width": 750,
    "height": 750
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "7 - 14", "metric": "3 - 6"},
        "id": "ebur",
        "name": "European Burmese",
        "cfa_url": "http://cfa.org/Breeds/BreedsCJ/EuropeanBurmese.aspx",
        "temperament": "Sweet, Affectionate, Loyal",
        "origin": "Burma",
        "country_codes": "MM",
        "country_code": "MM",
        "description":
            "The European Burmese is a very affectionate, intelligent, and loyal cat. They thrive on companionship and will want to be with you, participating in everything you do. While they might pick a favorite family member, chances are that they will interact with everyone in the home, as well as any visitors that come to call. They are inquisitive and playful, even as adults. ",
        "life_span": "10 - 15",
        "indoor": 0,
        "lap": 1,
        "alt_names": "",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "cat_friendly": 4,
        "dog_friendly": 4,
        "energy_level": 4,
        "grooming": 1,
        "health_issues": 4,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 5,
        "stranger_friendly": 5,
        "vocalisation": 4,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "hypoallergenic": 0
      }
    ],
    "id": "DZzcGANt5",
    "url": "https://cdn2.thecatapi.com/images/DZzcGANt5.jpg",
    "width": 2048,
    "height": 1365
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "12 - 18", "metric": "5 - 8"},
        "id": "mcoo",
        "name": "Maine Coon",
        "cfa_url": "http://cfa.org/Breeds/BreedsKthruR/MaineCoon.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/maine-coon",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/maine-coon",
        "temperament": "Adaptable, Intelligent, Loving, Gentle, Independent",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description":
            "They are known for their size and luxurious long coat Maine Coons are considered a gentle giant. The good-natured and affable Maine Coon adapts well to many lifestyles and personalities. She likes being with people and has the habit of following them around, but isn’t needy. Most Maine Coons love water and they can be quite good swimmers.",
        "life_span": "12 - 15",
        "indoor": 0,
        "lap": 1,
        "alt_names":
            "Coon Cat, Maine Cat, Maine Shag, Snowshoe Cat, American Longhair, The Gentle Giants",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 3,
        "grooming": 3,
        "health_issues": 3,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 3,
        "stranger_friendly": 5,
        "vocalisation": 1,
        "experimental": 0,
        "hairless": 0,
        "natural": 1,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Maine_Coon",
        "hypoallergenic": 0,
        "reference_image_id": "OOD3VXAQn"
      }
    ],
    "id": "-8roc4viS",
    "url": "https://cdn2.thecatapi.com/images/-8roc4viS.jpg",
    "width": 750,
    "height": 1125
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "5 - 11", "metric": "2 - 5"},
        "id": "rblu",
        "name": "Russian Blue",
        "cfa_url": "http://cfa.org/Breeds/BreedsKthruR/RussianBlue.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/russian-blue-nebelung",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/russian-blue",
        "temperament":
            "Active, Dependent, Easy Going, Gentle, Intelligent, Loyal, Playful, Quiet",
        "origin": "Russia",
        "country_codes": "RU",
        "country_code": "RU",
        "description":
            "Russian Blues are very loving and reserved. They do not like noisy households but they do like to play and can be quite active when outdoors. They bond very closely with their owner and are known to be compatible with other pets.",
        "life_span": "10 - 16",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Archangel Blue, Archangel Cat",
        "adaptability": 3,
        "affection_level": 3,
        "child_friendly": 3,
        "dog_friendly": 3,
        "energy_level": 3,
        "grooming": 3,
        "health_issues": 1,
        "intelligence": 3,
        "shedding_level": 3,
        "social_needs": 3,
        "stranger_friendly": 1,
        "vocalisation": 1,
        "experimental": 0,
        "hairless": 0,
        "natural": 1,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Russian_Blue",
        "hypoallergenic": 1,
        "reference_image_id": "Rhj-JsTLP"
      }
    ],
    "id": "tHKLZkKZG",
    "url": "https://cdn2.thecatapi.com/images/tHKLZkKZG.jpg",
    "width": 3504,
    "height": 2336
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "6 - 12", "metric": "3 - 5"},
        "id": "sphy",
        "name": "Sphynx",
        "cfa_url": "http://cfa.org/Breeds/BreedsSthruT/Sphynx.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/sphynx",
        "vcahospitals_url":
            "https://vcahospitals.com/know-your-pet/cat-breeds/sphynx",
        "temperament": "Loyal, Inquisitive, Friendly, Quiet, Gentle",
        "origin": "Canada",
        "country_codes": "CA",
        "country_code": "CA",
        "description":
            "The Sphynx is an intelligent, inquisitive, extremely friendly people-oriented breed. Sphynx commonly greet their owners  at the front door, with obvious excitement and happiness. She has an unexpected sense of humor that is often at odds with her dour expression.",
        "life_span": "12 - 14",
        "indoor": 0,
        "lap": 1,
        "alt_names": "Canadian Hairless, Canadian Sphynx",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 3,
        "grooming": 2,
        "health_issues": 4,
        "intelligence": 5,
        "shedding_level": 1,
        "social_needs": 5,
        "stranger_friendly": 5,
        "vocalisation": 5,
        "experimental": 0,
        "hairless": 1,
        "natural": 0,
        "rare": 1,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Sphynx_(cat)",
        "hypoallergenic": 1,
        "reference_image_id": "BDb8ZXb1v"
      }
    ],
    "id": "k8bHZo-Bj",
    "url": "https://cdn2.thecatapi.com/images/k8bHZo-Bj.jpg",
    "width": 1140,
    "height": 760
  },
  {
    "breeds": [
      {
        "weight": {"imperial": "7 - 15", "metric": "3 - 7"},
        "id": "toyg",
        "name": "Toyger",
        "vetstreet_url": "http://www.vetstreet.com/cats/toyger",
        "temperament": "Playful, Social, Intelligent",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description":
            "The Toyger has a sweet, calm personality and is generally friendly. He's outgoing enough to walk on a leash, energetic enough to play fetch and other interactive games, and confident enough to get along with other cats and friendly dogs.",
        "life_span": "12 - 15",
        "indoor": 0,
        "lap": 1,
        "alt_names": "",
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 5,
        "grooming": 1,
        "health_issues": 2,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 3,
        "stranger_friendly": 5,
        "vocalisation": 5,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Toyger",
        "hypoallergenic": 0,
        "reference_image_id": "O3F3_S1XN"
      }
    ],
    "id": "HW1MGAuGL",
    "url": "https://cdn2.thecatapi.com/images/HW1MGAuGL.jpg",
    "width": 1600,
    "height": 1200
  }
];
